version: '3.3'

services:
  app:
    build: .
    ports:
      - "9090:80"
    volumes:
      - ./src:/var/www/html
    env_file:
      - ./.env
  db:
    image: mysql
    ports: 
      - 3306:3306
    environment:
     DB_USER: ${DB_USER}
     DB_NAME: ${DB_NAME}
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}